title: "MELT"
description: Documentation of the Matching and EvaLuation Toolkit (MELT).
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false

#title: "Matching EvaLuation Toolkit (MELT)"
#description: MELT documentation
#remote-theme: "just-the-docs"
#base-url: ""
#url: ""


#footer_content: "MELT Team 2021"

back_to_top: true
back_to_top_text: "Back to top"
